### ISSUE TITLE
Best way to size the icon and text?

### ISSUE THREAD

**Issue by robertocarroll** [wearethoughtfox/amnesty-dp-2016#40]
The figures can get quite big, e.g. 1000+ any suggestions how to layout the icon and the figure? At the moment its a float left with a width of 16% on the icon and 74% on the text but is there a better way? 

Smaller
![map_of_death_penalties_and_execution_around_the_world_-_amnesty_international 2](https://cloud.githubusercontent.com/assets/1565953/16921869/4042b546-4d0b-11e6-84e9-c8728d323c91.png)

Larger 
![map_of_death_penalties_and_execution_around_the_world_-_amnesty_international](https://cloud.githubusercontent.com/assets/1565953/16921862/38c1a278-4d0b-11e6-8fc8-d73b50081e31.png)

**Comment by robertocarroll** [comment]
I've gone with fittext on this with some tweaks to the compression. I think it works OK, but would love to hear what you think.

**Comment by pauldwaite** [comment]
@robertocarroll: I’ve thought of two possible alternatives to fittext. I could try implementing one of these (or both if I try one and it doesn’t work) if we’re not happy with how fittext is working, or if we think this would be better.

### Fixed width sidebar in wide layout, smaller text in narrow layout
1. In the wide layout, fix the width of the “sidebar” (instead of having it be 25% of the viewport width), and have the map fill up the remaining space. The text in the sidebar will no longer need to scale, because it always has the same width availabe.
2. In the narrow layout, set the the text sizes to fit the minimum supported viewport width. If displayed in a larger viewport, there will be more white space around the text.

### Size text using vw units

This isn’t supported by IE 8, but you can use the vw (viewport width) unit to size text. It may be possible to use this to have the text size adjust to the available width.

Fixed smaller text sizes could be included for IE 8.

**Comment by robertocarroll** [comment]
Both of these ideas sound good. There's no need for the infobox to be fluid and it would make things easier. Anything to get rid of extra code.
