### ISSUE TITLE
Last-minute clean up

### ISSUE THREAD

**Issue by robertocarroll** [wearethoughtfox/amnesty-dp-2016#58]
- [x]  Tooltip positions. On the smaller screens version they go a bit crazy in their positions.
Perhaps needs an if statement to correct the tooltip position on small screens? 

- [x]  Infobox to map ratio on things like iPads. An extra media query tweak that takes that width down to say 250px when its around iPad width? 

- [x] Implement a preloader to avoid the ugly HTML until all the data has loaded? It doesn’t have to do anything other than say “loading”. 

- [x] Merge into gh-pages (no longer serving live site).

- [x] Check breakpoints - the point at which it goes to mobile version.

- [ ] Tooltips - perhaps check if they are at the top or the bottom of the screen and adjust accordingly.  

- [ ] Width of the timeline when the screen size changes. Call the setupSlider (749) again to match the width to the window width when it resizes? 

- [x] "Thin" wide screens don't have enough height to incorporate the timeline. Possible approach? 
See #59

(https://cloud.githubusercontent.com/assets/1565953/21189399/f8097bbe-c237-11e6-917e-ec112347e7dd.png)

- [x] In **embed** the small screen version is cut off. _This was due to not using pym.js_

![test___amnesty_international](https://cloud.githubusercontent.com/assets/1565953/21188386/b1a3173c-c234-11e6-9dbf-4a85709ee91b.png)

**Comment by pauldwaite** [comment]
Summarised update:

> Tooltip positions. On the smaller screens version they go a bit crazy in their positions.

Pull requested created to hopefully fix this bug: https://github.com/wearethoughtfox/amnesty-dp-2016/pull/60

> Infobox to map ratio on things like iPads. An extra media query tweak that takes that width down to say 250px when its around iPad width?

Branch created that implements the small-screen layout up to 784 pixels wide. Take a look and see where you think the cut-off should be: https://github.com/wearethoughtfox/amnesty-dp-2016/tree/small-screen-view-up-to-784

> Implement a preloader to avoid the ugly HTML until all the data has loaded? It doesn’t have to do anything other than say “loading”.

Pull request created. Have a look and see what you think: https://github.com/wearethoughtfox/amnesty-dp-2016/pull/61

> Width of the timeline when the screen size changes. Call the setupSlider (749) again to match the width to the window width when it resizes?

Pull request created. Have a look and see what you think: https://github.com/wearethoughtfox/amnesty-dp-2016/pull/62

> Disable scrollwheel zoom so it doesn't zoom as someone scrolls down the page.
http://bl.ocks.org/phil-pedruco/7051484

I’ve had a go at this in a branch (https://github.com/wearethoughtfox/amnesty-dp-2016/tree/disable-scrollwheel-zoom), by:

- In the zoom in/out button functions, saving the `target_scale` variable globally, as `savedZoomScale`.

- In the `move()` function, setting the `s` (i.e. “scale”) variable to this saved value, rather than getting it from `d3.event.scale` (which I think supplies the updated value based on the user’s scroll or pinch or whatever action).

This almost does it, but essentially it seems that while scrollwheel zooming in doesn’t have any effect, scrollwheel zooming out *does* do something (the map sort of moves up a bit). I think maybe there’s something going on with scaleExtent as well?

> "Thin" wide screens don't have enough height to incorporate the timeline. Possible approach?
See #59

> In embed the small screen version is cut off

As far as I can tell, these are either as-designed, or caused by Amnesty not using Pym on their parent page.
